Saved train data ...
Saved valid data ...
Saved test data ...
Size : 33280
Size : 5888
Size : 6912
Traceback (most recent call last):
  File "src/main.py", line 123, in <module>
    runner.train_model(logger)
  File "src/main.py", line 99, in train_model
    Engine.run_step(logger)
  File "/home/kwlee/Projects_gflas/Team_BI/Projects/WSCNN/src/engine/train.py", line 53, in run_step
    train_losses = self.train(epoch)
  File "/home/kwlee/Projects_gflas/Team_BI/Projects/WSCNN/src/engine/train.py", line 87, in train
    outputs = self.framework(X)
  File "/home/kwlee/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kwlee/Projects_gflas/Team_BI/Projects/WSCNN/src/modeling/wscnnlstm.py", line 62, in forward
    x = self.predictor(x)
  File "/home/kwlee/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kwlee/anaconda3/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/kwlee/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kwlee/anaconda3/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 167, in forward
    return F.batch_norm(
  File "/home/kwlee/anaconda3/lib/python3.8/site-packages/torch/nn/functional.py", line 2281, in batch_norm
    return torch.batch_norm(
RuntimeError: running_mean should contain 256 elements not 32
